import React from 'react';
import Products from '../../components/Products';
import Head from 'next/head'
const product = ({data}) => {
    
    return (
        <div className=' min-h-screen py-10'>
                     <Head>
        <title>Ghazachi | products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon2.ico" />
      </Head>
            <div className=' pt-20'>
            <div className='  grid grid-cols-1  w-full flex-col mx-auto   sm:grid sm:grid-cols-2  lg:grid-cols-3   xl:grid-cols-4 gap-4'>
            {
                    data.map(item => {
                        return  <Products key={item.idMeal} items={item} />
                    })
                }
            </div>
                        
                  
                
            </div>
        </div>
    );
};

export default product;

export async function getStaticProps(context) {
    const getApi = await fetch('https://www.themealdb.com/api/json/v1/1/filter.php?a=Canadian')
    const data = await getApi.json()
   
  return {
  props: {
      data :data.meals 
  }, // will be passed to the page component as props
  }
  }