import React from 'react';
import Image from 'next/image'
import {GoLocation} from 'react-icons/go'
import {AiFillPhone,AiOutlineMail} from 'react-icons/ai'
import { GoogleMap, useLoadScript, Marker } from "@react-google-maps/api";
import MyMapComponent from '../components/MyMapComponent'
import Head from 'next/head'

import {Formik,Form,ErrorMessage,Field} from 'formik'
import * as yup from 'yup';

const about = () => {

       
            const initialValues ={
                name: '',
                email: '',
                subject:'',
                textArea :''
            }
          const  onSubmit = (data) => {
                console.log(data);
            }
      
                const validationSchema = yup.object({
                   name : yup.string()
                   .required('پر کردن این قسمت الزامی میباشد')
                   .trim()
                   ,
                   email: yup.string()
                   .email('آدرس ایمیل معتبر نمیباشد')
                   .required('پر کردن این قسمت الزامی میباشد')
                   .trim()
                   ,
                   textArea : yup.string()
                   .required('پر کردن این قسمت الزامی میباشد')
                   .trim()
                   ,
                   subject : yup.string()
                   .required('پر کردن این قسمت الزامی میباشد')
                   .trim()
                })


        const handleSubmit = (e) => {
             
                console.log('sex');
                e.preventDefault()
        }

    return (

        <div className=' min-h-screen'>
            <Head>
        <title>Ghazachi | About Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon2.ico" />
      </Head>
                <div className="pt-[58px] z-[30]">
      <div className="h-[195px] w-full imgBg   relative z-[10]  ">
        <div className=" absolute  inset-0 bg-red-600 opacity-[.5]  z-10 "></div>
      </div>
        </div>



            {/* first section */}
            <div   className='mt-20 max-w-[65%] mx-auto flex   space-y-16 lg:space-y-0  py-10 lg:py-0    flex-col   justify-center lg:flex-row lg:justify-between'>
                {/* about us */}
                <div className=' space-y-5  flex flex-col justify-center items-center  lg:block '>
                    <p className=' text-blue-400 '>ارتباط با ما</p>
                    <div className=''>
                        <p className='text-2xl'>اگر سوالی دارید دریغ نکنید</p>
                        <span className=' text-2xl  w-full '>از ما بپرسید</span> 
                    </div>
                    <div className=' space-y-3 pt-5 lg:pt-10'>
                      <div className='flex  '>
                        <span ><GoLocation className='bg-red-500 w-[30px] rounded-full p-[.4rem] h-[30px]  text-white '/></span>
                        <p className=' mr-[5%]'>آمل دریای 16 ساختمان 33</p>
                      </div>  
                      <div className='flex'>
                        <span ><AiFillPhone className='bg-red-500 w-[30px] rounded-full p-[.4rem] h-[30px]  text-white '/></span>
                        <p className=' mr-[5%]'>091126542323</p>
                      </div>  
                      <div className='flex'>
                        <span ><AiOutlineMail className='bg-red-500 w-[30px] rounded-full p-[.4rem] h-[30px]  text-white '/></span>
                        <p className=' mr-[5%]'>sda@gmail.com</p>
                      </div>  
                    </div>

                </div>

                {/* form */}
                <Formik onSubmit={onSubmit}
                
                initialValues={initialValues}
                validationSchema={validationSchema}>
                           {({ errors, touched }) => (
  <Form  className=' space-y-7 '  >
  <div className={`flex    flex-col  lg:flex-row lg:justify-between  relative   w-full mx-[3px] `}>
      <Field   style={{border:`${errors.name && touched.name ?' 2px solid red' : '2px solid #FFCBC1'}`}}   placeholder='نام ' className={`     justify-between   focus-visible:outline-none px-2 placeholder:px-2  border-2 border-[#FFCBC1] p-1 rounded-md  `} type="text" name="name" id="name" />
         {errors.name && touched.name ?  <div className=' lg:absolute bottom-[-70%] right-[0%] text-red-500 text-sm'>{errors.name}</div> : null}                   
      <Field   style={{border:`${errors.email && touched.email ?' 2px solid red' : '2px solid #FFCBC1'}`}}   placeholder='ایمیل' className={` ${!errors.name ? 'mt-5 lg:mt-0' : 'mt-5 lg:mt-0'}  focus-visible:outline-none py-1 px-2 placeholder:px-2 border-2 border-[#FFCBC1] p-1 rounded-md`} type="text" name="email" id="email" />
      {errors.email && touched.email ?  <div className=' lg:absolute bottom-[-70%] left-[0%] text-red-500 text-sm'>{errors.email}</div> : null}
  </div>
 
  <div className=' mt-6'>
      <Field   style={{border:`${errors.subject && touched.subject ?' 2px solid red' : '2px solid #FFCBC1'}`}}    placeholder='موضوع' className='  focus-visible:outline-none px-2   border-2 border-[#FFCBC1] p-1 rounded-md w-full' type="text" name="subject" id="subject"  />
      {errors.subject && touched.subject ?  <div className='  text-red-500 text-sm'>{errors.subject}</div> : null}

  </div>
  
      <div className='mt-5   '>
      <Field   style={{border:`${errors.textArea && touched.textArea ?' 2px solid red' : '2px solid #FFCBC1'}`}} as='textarea'  placeholder='لطفا آنچه را که نیاز دارید توصیف کنید' className="focus:outline-none  py-1 resize-none rounded-md border-2 w-full border-[#FFCBC1] px-2 h-28 " name='textArea' id='textArea'></Field>
      {errors.textArea && touched.textArea ?  <div className='  text-red-500 text-sm'>{errors.textArea}</div> : null}
                            
      </div>
          <div className=' mt-5 '>  <button type='submit'  className=' w-full  text-red-500 py-2 rounded-md bg-[#FFCBC1]'><span>ارسال پیام</span></button></div>
    
  
  </Form> 
       )}
                </Formik>
            </div>



             {/* second section */}
            <div className='pt-20 mt-10'>
                        <MyMapComponent/>
                            



            </div>
        </div>
    );
};

export default about;

